// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MBGenerator.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class imageRequest : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""imageRequest"",""namespace"":""MBGenerator.avro"",""fields"":[{""name"":""display_x"",""type"":""int""},{""name"":""display_y"",""type"":""int""},{""name"":""min_x"",""type"":""double""},{""name"":""min_y"",""type"":""double""},{""name"":""max_x"",""type"":""double""},{""name"":""max_y"",""type"":""double""},{""name"":""depth"",""type"":""int""},{""name"":""connectionId"",""type"":""string""}]}");
		private int _display_x;
		private int _display_y;
		private double _min_x;
		private double _min_y;
		private double _max_x;
		private double _max_y;
		private int _depth;
		private string _connectionId;
		public virtual Schema Schema
		{
			get
			{
				return imageRequest._SCHEMA;
			}
		}
		public int display_x
		{
			get
			{
				return this._display_x;
			}
			set
			{
				this._display_x = value;
			}
		}
		public int display_y
		{
			get
			{
				return this._display_y;
			}
			set
			{
				this._display_y = value;
			}
		}
		public double min_x
		{
			get
			{
				return this._min_x;
			}
			set
			{
				this._min_x = value;
			}
		}
		public double min_y
		{
			get
			{
				return this._min_y;
			}
			set
			{
				this._min_y = value;
			}
		}
		public double max_x
		{
			get
			{
				return this._max_x;
			}
			set
			{
				this._max_x = value;
			}
		}
		public double max_y
		{
			get
			{
				return this._max_y;
			}
			set
			{
				this._max_y = value;
			}
		}
		public int depth
		{
			get
			{
				return this._depth;
			}
			set
			{
				this._depth = value;
			}
		}

		public string connectionId
		{
			get
			{
				return this._connectionId;
			}
			set
			{
				this._connectionId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.display_x;
			case 1: return this.display_y;
			case 2: return this.min_x;
			case 3: return this.min_y;
			case 4: return this.max_x;
			case 5: return this.max_y;
			case 6: return this.depth;
			case 7: return this.connectionId;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.display_x = (System.Int32)fieldValue; break;
			case 1: this.display_y = (System.Int32)fieldValue; break;
			case 2: this.min_x = (System.Double)fieldValue; break;
			case 3: this.min_y = (System.Double)fieldValue; break;
			case 4: this.max_x = (System.Double)fieldValue; break;
			case 5: this.max_y = (System.Double)fieldValue; break;
			case 6: this.depth = (System.Int32)fieldValue; break;
			case 7: this.connectionId = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
