// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MBGenerator.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class imageResponse : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"imageResponse\",\"namespace\":\"MBGenerator.avro\",\"fields\":[" +
				"{\"name\":\"display_x\",\"type\":\"int\"},{\"name\":\"display_y\",\"type\":\"int\"},{\"name\":\"url" +
				"\",\"type\":\"string\"},{\"name\":\"connectionId\",\"type\":\"string\"}]}");
		private int _display_x;
		private int _display_y;
		private string _connectionId;
		private string _url;
		public virtual Schema Schema
		{
			get
			{
				return imageResponse._SCHEMA;
			}
		}
		public int display_x
		{
			get
			{
				return this._display_x;
			}
			set
			{
				this._display_x = value;
			}
		}
		public int display_y
		{
			get
			{
				return this._display_y;
			}
			set
			{
				this._display_y = value;
			}
		}

		public string connectionId
		{
			get
			{
				return this._connectionId;
			}
			set
			{
				this._connectionId = value;
			}
		}
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				this._url = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.display_x;
			case 1: return this.display_y;
			case 2: return this.url;
			case 3: return this.connectionId;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.display_x = (System.Int32)fieldValue; break;
			case 1: this.display_y = (System.Int32)fieldValue; break;
			case 2: this.url = (System.String)fieldValue; break;
			case 3: this.connectionId = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
