apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-server1
  name: kafka-server1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-net: "true"
        io.kompose.service: kafka-server1
    spec:
      containers:
      - env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: "imageReq:10:1"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-server:2181
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-server1
        image: wurstmeister/kafka:latest
        name: kafka-server1
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}
