apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-server1
  name: kafka-server1
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    io.kompose.service: kafka-server1
status:
  loadBalancer: {}
