apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-schema-registry
  name: kafka-schema-registry
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-net: "true"
        io.kompose.service: kafka-schema-registry
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: kafka-schema-registry
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper-server:2181
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        image: confluentinc/cp-schema-registry
        name: kafka-schema-registry
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
