apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: csmandelbrot
  name: mbgen-lb-service
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: mbgenerator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80