apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: mbgenerator
  name: mbgenerator
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-net: "true"
        io.kompose.service: mbgenerator
    spec:
      containers:
      - image: yamniloc/mbgenerator:latest
        name: mbgenerator
        resources: {}
      restartPolicy: Always
status: {}
