apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: mbimagebuilder
  name: mbimagebuilder
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-net: "true"
        io.kompose.service: mbimagebuilder
    spec:
      containers:
      - image: yamniloc/mbimagebuilder:latest
        name: mbimagebuilder
        resources: {}
        env:
        - name: SECRET_MONGO_PASSWORD
          value: password123
        - name: SECRET_MONGO_USER
          value: mongo_user
      restartPolicy: Always
status: {}
