apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/kafka-net: "true"
        io.kompose.service: mongodb
    spec:
      volumes:
      - name: mongo-init-configmap-volume
        configMap:
          name: mongoinit
      containers:
      - args:
        - mongod
        - --logpath=/tmp/mongolog
        env:
        - name: MONGO_INITDB_DATABASE
          value: MBImageDatabase
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password123
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        image: mongo:latest
        name: mongodb
        volumeMounts:
        - name: mongo-init-configmap-volume
          mountPath: /docker-entrypoint-initdb.d
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
