{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mbgenerator.serviceAccountName" . }}
  labels:
{{ include "mbgenerator.labels" . | nindent 4 }}
{{- end -}}
