apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\colin\Kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper-server
  name: zookeeper-server
spec:
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181
  selector:
    io.kompose.service: zookeeper-server
status:
  loadBalancer: {}
